# UserJY - Github action to autobuild Hakyll static pages on push

name: Autobuild Hakyll Site

# Controls when the workflow will run
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: step 1
        run: |
             pwd
             ls

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}
          path: |
            ~/.stack
            ~/.stack-work
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: step 2
        run: |
             pwd
             ls

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.3' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: step 3
        run: |
             pwd
             ls

      - name: Autofinding hakyll blog full path
        run: |
            echo "tpath=$( find ${{ github.workspace }} -name '*.cabal' | head )" >> $GITHUB_ENV
           
      - name: Detect executable name through cabal file
        run: |
            echo "autotarget=$(grep "executable" $tpath | cut -d' ' -f 2)" >> $GITHUB_ENV
            

      - name: Checking
        run: echo $autotarget
      #- run: stack --system-ghc build --only-dependencies
      
      - name: Stack Installing hakyll environment
        run: stack install --fast --flag hakyll:-previewserver --flag hakyll:-watchserver

      - name: step 4
        run: |
             pwd
             ls
             
            
      - name: Cleaning hakyll
        run: stack exec -- $autotarget clean
            
      - name: Building hakyll static pages
        run: stack exec -- $autotarget build

      - name: detect Distro for stork
        run: |
             if cat /etc/*-release | grep "redhat\|centos"; then echo "STORK=$(echo 'stork-amazon-linux')" >> $GITHUB_ENV; fi;
             if cat /etc/*-release | grep "ubuntu\|debian"; then echo "STORK=$(echo 'stork-ubuntu-20-04')" >> $GITHUB_ENV; fi;

      - name: Build stork search index
        run: ./$STORK build --input "./docs/searchindex.toml" --output "./docs/storksearch.st"

      - name: step 5
        run: |
             pwd
             ls

      # Runs a set of commands using the runners shell
      - name: commit built site
        run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add .
           if ! git diff-index --quiet HEAD --; then
              git commit -m "Autobuild Hakyll site github action commit"
              git push
              echo "pushing changes"
           fi           
